version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: make circleci
      - run: make build-docker-image
      - run: make build-in-docker
      - run: make store-artifacts
      - run: make validate-in-docker
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release-in-docker
              PACKAGECLOUD_REPOSITORY=dokku/dokku make release-packagecloud-in-docker
            else
              make release-packagecloud-in-docker
            fi
