version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/josegonzalez/go-procfile-util
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching:
      - run: make circleci
      - run: make deps
      - run: make build
      - run: make store-artifacts
      - run: make build-validate
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release
            fi
